// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uocfjxteyrjnihemezgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvY2ZqeHRleXJqbmloZW1lemdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjE0MjIsImV4cCI6MjA2NTk5NzQyMn0.iTMDpa3feA_fxNZF2J3tiVRN3dJZWoEE1MJwFxOx4N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);